### ISSUE TITLE
Path caching issue in file browser when navigating to different bucket

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/browser#45]
When you navigate deep into a path, and then navigate out and switch buckets, you still see the first path associated with the previous bucket you were in.

https://storjlabs.atlassian.net/browse/USR-1716

**Comment by montyanderson** [comment]
Pushed a possible fix for this https://github.com/storj/browser/commit/4038f6fc5b2e730868331b32fe48c975e1692785
