### ISSUE TITLE
Display warning if user tries to create folder with periods or slashes

### ISSUE THREAD

**Issue by super3** [storj/browser#48]
Spinner is visible while creating new folder if invalid characters like `.` , `..`, `/` are entered then ENTER key is pressed.

![image](https://user-images.githubusercontent.com/15882196/112024002-c5b11880-8b59-11eb-8b21-7239924ce0f0.png)

**Comment by montyanderson** [comment]
We shouldn't let them click `save folder` if you have those characters in your folder name.

**Comment by super3** [comment]
Just turn the input red for now
